[package]
name = "massa_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee", branch = "master", features = ["client"] }
massa_models = { path = "../massa-models" }
